---
abstract: 'A quick and easy way to build simple web applications'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper::Concise: 2.020
  Moo: 0.009014
  Plack: 0.9968
  Syntax::Keyword::Gather: 1.001
  warnings::illegalproto: 0.001
version: 0.018
