---
abstract: 'A quick and easy way to build simple web applications'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Data::Dumper::Concise: '2.020'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Web-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Encode: '0'
  Exporter: '5.57'
  Moo: '0.009014'
  Plack: '0.9968'
  Scalar::Util: '0'
  Syntax::Keyword::Gather: '1.001'
  perl: '5.006'
  strictures: '1'
  warnings::illegalproto: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Web-Simple
  repository: git://git.shadowcat.co.uk/catagits/Web-Simple.git
version: '0.030'
