--- #YAML:1.0
name:               Web-Simple
version:            0.008
abstract:           A quick and easy way to build simple web applications
author:
    - mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper::Concise:  2.020
    Moo:                  0.009005
    Plack:                0.9968
    Syntax::Keyword::Gather:  1.001
    warnings::illegalproto:  0.001
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
